### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by akkadaya** [calavera/query-map-rs#13]
There is a typo in documentation "Return the first **_elelemnt_** associated with a key"

https://docs.rs/query_map/latest/query_map/struct.QueryMap.html#method.first
https://github.com/calavera/query-map-rs/blob/fd13ea4264048acbea79d4e9d9e3b1c8c3e9f792/src/lib.rs#L91

**Comment by calavera** [comment]
feel free to open a PR to fix it

**Comment by DK26** [comment]
Here is my PR #14 ;-)
